<a href="https://colab.research.google.com/github/rosariocv/Rosario/blob/master/pysus.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Usando o PySUS no Colab

In [ ]:
# @title Installing PySUS { run: "auto", vertical-output: true, display-mode: "form" }
!pip install pysus # caso receba uma mensagem de timeout, basta reiniciar o runtime e executar de novo esta célula

Requirement already satisfied: pysus in /usr/local/lib/python3.10/dist-packages (0.14.0)
Requirement already satisfied: Unidecode<2.0.0,>=1.3.6 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.3.8)
Requirement already satisfied: aioftp<0.22.0,>=0.21.4 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.21.4)
Requirement already satisfied: bigtree<0.13.0,>=0.12.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.12.5)
Requirement already satisfied: cffi==1.15.1 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.15.1)
Requirement already satisfied: dateparser<2.0.0,>=1.1.8 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.2.0)
Requirement already satisfied: dbfread==2.0.7 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.0.7)
Requirement already satisfied: elasticsearch[preprocessing]==7.16.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (7.16.2)
Requirement already satisfied: fastparquet>=2023.10.1 in /usr/local/lib/python3.10/dist-packages (from pysus) (2024.5.0)
Requirement already satisfied: humanize<5.0.0,>=4.8.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.9.0)
Requirement already satisfied: loguru<0.7.0,>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (0.6.0)
Requirement already satisfied: numpy==1.26.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.26.2)
Requirement already satisfied: pandas>=2.1.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.2.2)
Requirement already satisfied: pyarrow>=11.0.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (14.0.2)
Requirement already satisfied: pycparser==2.21 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.21)
Requirement already satisfied: pyreaddbc>=1.1.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (1.2.0)
Requirement already satisfied: python-dateutil==2.8.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.8.2)
Requirement already satisfied: tqdm==4.64.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.64.0)
Requirement already satisfied: typing-extensions<5.0.0,>=4.9.0 in /usr/local/lib/python3.10/dist-packages (from pysus) (4.12.2)
Requirement already satisfied: urwid<3.0.0,>=2.1.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (2.6.14)
Requirement already satisfied: wget<4.0,>=3.2 in /usr/local/lib/python3.10/dist-packages (from pysus) (3.2)
WARNING: elasticsearch 7.16.2 does not provide the extra 'preprocessing'
Requirement already satisfied: urllib3<2,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from elasticsearch[preprocessing]==7.16.2->pysus) (1.26.19)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/dist-packages (from elasticsearch[preprocessing]==7.16.2->pysus) (2024.6.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil==2.8.2->pysus) (1.16.0)
Requirement already satisfied: pytz in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2023.4)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (2024.5.15)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/dist-packages (from dateparser<2.0.0,>=1.1.8->pysus) (5.2)
Requirement already satisfied: cramjam>=2.3 in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (2.8.3)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (2023.6.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from fastparquet>=2023.10.1->pysus) (24.1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.10/dist-packages (from pandas>=2.1.0->pysus) (2024.1)
Requirement already satisfied: pyyaml>=6 in /usr/local/lib/python3.10/dist-packages (from pyreaddbc>=1.1.0->pysus) (6.0.1)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from urwid<3.0.0,>=2.1.2->pysus) (0.2.13)

In [ ]:
# @title Importando o PySUS { display-mode: "form" }
from pysus.online_data import SINAN
import pandas as pd

In [ ]:
# @title Interagindo com o SINAN { run: "auto" }
import ipywidgets as widgets
from IPython.display import display
button = widgets.Button(description="Clique para mostrar lista de Agravos no SINAN!")
output = widgets.Output()
agrs = SINAN.list_diseases()

def on_button_clicked(b):
  # Display the message within the output widget.
  with output:
    for a in agrs:
      print(a)


button.on_click(on_button_clicked)
display(button, output)

Button(description='Clique para mostrar lista de Agravos no SINAN!', style=ButtonStyle())

Output()

In [ ]:
# @title Quais anos estão disponíveis? { run: "auto", display-mode: "form" }
Agravo = "deng" # @param ["deng", "mala"]
SINAN.get_available_years(Agravo)

[2000,
 2001,
 2002,
 2003,
 2004,
 2005,
 2006,
 2007,
 2008,
 2009,
 2010,
 2011,
 2012,
 2013,
 2014,
 2015,
 2016,
 2017,
 2018,
 2019,
 2020,
 2021,
 2022,
 2023,
 2024]

In [ ]:
# @title Baixando os dados { run: "auto", display-mode: "form" }
Ano = 2011 # @param {type:"slider", min:2010, max:2022, step:1}
pth = SINAN.download(Agravo, Ano)
pd.read_parquet(pth)

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,HOSPITALIZ,DT_INTERNA,UF,MUNICIPIO,TP_SISTEMA
0,2,A90,20110925,201139,2011,35,354980,1354,2096854,20110924,...,,,,,,2,,,,
1,2,A90,20110506,201118,2011,33,330455,,2273179,20110505,...,,,,,,1,20110506,33,330455,1
2,2,A90,20110127,201104,2011,13,130260,5584,2012472,20110122,...,,,,,,2,,,,1
3,2,A90,20110226,201108,2011,33,330455,,2270609,20110218,...,,,,,,2,,,,1
4,2,A90,20110706,201127,2011,33,330455,,2269384,20110628,...,,,,,,9,,,,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1150006,2,A90,20110627,201126,2011,33,330190,,3784916,20110627,...,,,,,,,,,,
1150007,2,A90,20110107,201101,2011,41,411370,1371,2579170,20110104,...,,,,,,2,,,,2
1150008,2,A90,20110603,201122,2011,35,355220,1353,2708779,20110527,...,,,,,,2,,,,1
1150009,2,A90,20111222,201151,2011,15,150543,1495,2318865,20111217,...,,,,,,,,,,2
1150010,2,A90,20110315,201111,2011,33,330270,,2266733,20110309,...,,,,,,2,,,,1

In [ ]:
pth = SINAN.download('Chikungunya',2018)
pth

'/root/pysus/CHIKBR18.parquet'

In [ ]:
chik = pd.read_parquet(pth)

In [ ]:
chik

,TP_NOT,ID_AGRAVO,DT_NOTIFIC,SEM_NOT,NU_ANO,SG_UF_NOT,ID_MUNICIP,ID_REGIONA,ID_UNIDADE,DT_SIN_PRI,...,HEMATURA,SANGRAM,LACO_N,PLASMATICO,EVIDENCIA,PLAQ_MENOR,CON_FHD,COMPLICA,TP_SISTEMA,NDUPLIC_N
0,2,A92.0,20180926,201839,2018,33,330455,,6873960,20180919,...,,,,,,,,,2,
1,2,A92.0,20180619,201825,2018,33,330455,,6716911,20180614,...,,,,,,,,,2,
2,2,A92.0,20180421,201816,2018,33,330455,,6512925,20180418,...,,,,,,,,,2,
3,2,A92.0,20180514,201820,2018,33,330455,,2708167,20180512,...,,,,,,,,,2,
4,2,A92.0,20180619,201825,2018,33,330455,,2296306,20180603,...,,,,,,,,,2,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
118774,2,A92.0,20180222,201808,2018,26,261160,1497,0000434,20180216,...,,,,,,,,,2,
118775,2,A92.0,20180219,201808,2018,26,261160,1497,0020516,20180215,...,,,,,,,,,2,
118776,2,A92.0,20180319,201812,2018,26,261160,1497,0000477,20180319,...,,,,,,,,,2,
118777,2,A92.0,20180308,201810,2018,26,260090,1498,2714310,20180218,...,,,,,,,,,2,
118778,2,A92.0,20180203,201805,2018,26,261300,1499,2352133,20180203,...,,,,,,,,,2,

## Dados de Sífilis
existem 3 tipos de notificação de Sífilis no SINAN: adquirida, congênita e em gestantes.

In [ ]:
SINAN.download('Sífilis Adquirida',[2012,2013,2014])

('/root/pysus/SIFABR12.parquet',
 '/root/pysus/SIFABR13.parquet',
 '/root/pysus/SIFABR14.parquet')

In [ ]:
SINAN.download('Sífilis Congênita',[2012,2013,2014])

('/root/pysus/SIFCBR12.parquet',
 '/root/pysus/SIFCBR13.parquet',
 '/root/pysus/SIFCBR14.parquet')

In [ ]:
SINAN.download('Sífilis em Gestante',[2012,2013,2014])

('/root/pysus/SIFGBR12.parquet',
 '/root/pysus/SIFGBR13.parquet',
 '/root/pysus/SIFGBR14.parquet')

## Descompactando um DBC
O PySUS já converte os DBC do DATASUS em arquivos parquet. Mas caso você tenha um arquivo DBC baixado diretamente do DATASUS, pode descompacta-lo com a função abaixo. depois é só salvar no formato que você quiser.

In [ ]:
from pysus.utilities.readdbc import read_dbc

In [ ]:
dados = read_dbc('dados.dbc')
dados.to_csv('dados.csv.gz')